---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/oh-my-zsh.yml
    - include: tasks/vim-janus.yml
    - include: tasks/preferences.yml